#!/usr/bin/env bash
# This file contains scripts that are executed at different stages of package installation/upgrade/removal

# Color definitions for status messages
blueDark="\e[1;38;5;33m"     # Bold dark blue
lightBlue="\e[1;38;5;39m"    # Bold light blue
cyan="\e[1;38;5;45m"         # Bold cyan
white="\e[1;97m"             # Bold white
reset="\e[0m"                # Reset text formatting

# Print status messages
printMsg() {
    local message=$1
    echo -e "${blueDark}[${lightBlue}biglace${blueDark}]${reset} ${cyan}→${reset} ${white}${message}${reset}"
}

post_install() {
    printMsg "For incoming SSH/SFTP access, enable sshd explicitly: sudo systemctl enable --now sshd"
}
